version: "3"
services:
  data-science-env:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.conda
      args:
        - username=kohsuk
        - userid=1000
        - env=data-science
    container_name: jupyter
    image: kohsuk/data-science:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ../:/home/kohsuk/data-science